# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20151108_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='PaypalIpn',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', serialize=False, auto_created=True)),
                ('business', models.CharField(max_length=127)),
                ('charset', models.CharField(max_length=255)),
                ('custom', models.CharField(max_length=255)),
                ('notify_version', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('parent_txn_id', models.CharField(max_length=19)),
                ('receiver_email', models.CharField(max_length=254)),
                ('receiver_id', models.CharField(max_length=255)),
                ('residence_country', models.CharField(max_length=2)),
                ('test_ipn', models.IntegerField()),
                ('txn_id', models.CharField(max_length=255)),
                ('txn_type', models.CharField(max_length=255)),
                ('verify_sign', models.CharField(max_length=255)),
                ('address_country', models.CharField(max_length=64)),
                ('address_city', models.CharField(max_length=40)),
                ('address_country_code', models.CharField(max_length=64)),
                ('address_name', models.CharField(max_length=128)),
                ('address_state', models.CharField(max_length=40)),
                ('address_status', models.CharField(max_length=255)),
                ('address_street', models.CharField(max_length=200)),
                ('address_zip', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('payer_business_name', models.CharField(max_length=127)),
                ('payer_email', models.CharField(max_length=127)),
                ('payer_id', models.CharField(max_length=13)),
                ('auth_amount', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('auth_exp', models.CharField(max_length=28)),
                ('auth_id', models.CharField(max_length=19)),
                ('auth_status', models.CharField(max_length=255)),
                ('exchange_rate', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=16)),
                ('invoice', models.CharField(max_length=127)),
                ('item_name', models.CharField(max_length=127)),
                ('item_number', models.CharField(max_length=127)),
                ('mc_currency', models.CharField(max_length=32)),
                ('mc_fee', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('mc_gross', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('mc_handling', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('mc_shipping', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('memo', models.CharField(max_length=255)),
                ('num_cart_items', models.IntegerField(blank=True, null=True)),
                ('option_name1', models.CharField(max_length=64)),
                ('option_name2', models.CharField(max_length=64)),
                ('payer_status', models.CharField(max_length=255)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_gross', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('payment_status', models.CharField(max_length=255)),
                ('payment_type', models.CharField(max_length=255)),
                ('pending_reason', models.CharField(max_length=255)),
                ('protection_eligibility', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('reason_code', models.CharField(max_length=255)),
                ('remaining_settle', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('settle_amount', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('settle_currency', models.CharField(max_length=32)),
                ('shipping', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('shipping_method', models.CharField(max_length=255)),
                ('tax', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('transaction_entity', models.CharField(max_length=255)),
                ('auction_buyer_id', models.CharField(max_length=64)),
                ('auction_closing_date', models.DateTimeField(blank=True, null=True)),
                ('auction_multi_item', models.IntegerField(blank=True, null=True)),
                ('for_auction', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('amount', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('amount_per_cycle', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('initial_payment_amount', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('outstanding_balance', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('payment_cycle', models.CharField(max_length=255)),
                ('period_type', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('profile_status', models.CharField(max_length=255)),
                ('recurring_payment_id', models.CharField(max_length=255)),
                ('rp_invoice_id', models.CharField(max_length=127)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('amount1', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('amount2', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('amount3', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('mc_amount1', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('mc_amount2', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('mc_amount3', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('password', models.CharField(max_length=24)),
                ('period1', models.CharField(max_length=255)),
                ('period2', models.CharField(max_length=255)),
                ('period3', models.CharField(max_length=255)),
                ('reattempt', models.CharField(max_length=1)),
                ('recur_times', models.IntegerField(blank=True, null=True)),
                ('recurring', models.CharField(max_length=1)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('subscr_date', models.DateTimeField(blank=True, null=True)),
                ('subscr_effective', models.DateTimeField(blank=True, null=True)),
                ('subscr_id', models.CharField(max_length=19)),
                ('username', models.CharField(max_length=64)),
                ('case_creation_date', models.DateTimeField(blank=True, null=True)),
                ('case_id', models.CharField(max_length=255)),
                ('case_type', models.CharField(max_length=255)),
                ('receipt_id', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=32)),
                ('handling_amount', models.DecimalField(blank=True, null=True, max_digits=64, decimal_places=2)),
                ('transaction_subject', models.CharField(max_length=255)),
                ('ipaddress', models.CharField(blank=True, null=True, max_length=39)),
                ('flag', models.IntegerField()),
                ('flag_code', models.CharField(max_length=16)),
                ('flag_info', models.TextField()),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('from_view', models.CharField(blank=True, null=True, max_length=6)),
                ('mp_id', models.CharField(blank=True, null=True, max_length=128)),
            ],
            options={
                'managed': False,
                'db_table': 'paypal_ipn',
            },
        ),
    ]
